News
----

16 Jan 2014 (synagios.spk for ARM released to sourceforge)

* NEW - Nagrestconf for Synology Diskstation NAS devices.
+
The Synagios package includes nagios, pnp4nagios and nagrestconf.
+
I don't own an ARM device so the spk is completely untested - Use
at your own risk!

15 Jan 2014 (synagios.spk for x86 released to sourceforge)

* NEW - Nagrestconf for Synology Diskstation NAS devices.
+
The Synagios package includes nagios, pnp4nagios and nagrestconf.
+
Tested on a Synology Diskstation DS412+, DSM 4.3, Intel Atom.

13 Jan 2014 New version 1.169 (packages released to Sourceforge)

* Now in Beta. (Feature freeze)
+
Only bug fixes and plugins will be developed with version 1.x
+
* Added extra back-end checks and autocomplete for time periods.

09 Jan 2013 New version 1.168 (redhat 5/6 and debian packages released to Sourceforge)

* READ the Upgrade section before upgrading a version <1.165.

* Bug squashing.
06 Jan 2013 New version 1.165 (redhat 5/6 and debian packages released to Sourceforge)

* Important bug fixes. READ the Upgrade section before upgrading.

03 Jan 2013 New version 1.163 (redhat 5/6 and debian packages released to Sourceforge)

* New Backup & Restore plugin.

30 Dec 2013 New version 1.162 (redhat 5/6 and debian packages released to Sourceforge)

* Added Parent Template field to the Templates tab.
* Added project icon.

29 Dec 2013 New version 1.161 (redhat 5/6 and debian packages released to Sourceforge)

* Bug fixes

22 Dec 2013 New version 1.160 (redhat 5/6 and debian packages released to Sourceforge)

* The GUI now works in Internet Explorer 8, 9, 10 and 11.
* More fields have been added to the GUI for Host Templates, Service Templates, and Contacts.
* Added auto-completion to most applicable text entry boxes.
* Servicesets field in hosts now accepts multiple service sets. Service sets are added from left to right; any duplicate services are overwritten by the rightmost serviceset.
* The service sets can now be edited and reapplied to hosts using the edit host dialog.
* Bulk Tools, new `Add Hosts' tab: Allows bulk adding of hosts using csv files.
* Bulk Tools, new `Refresh Hosts' tab: Applies service sets to many hosts.
* Various bug fixes and extra validity checks.

18 Aug 2013 New version 1.158 https://sourceforge.net/projects/nagrestconf/files/[(Debian packages)]

17 Aug 2013 New version 1.158 https://sourceforge.net/projects/nagrestconf/files/[(Centos/Redhat RPMS)]

* Page tabs are now dynamic.
* Added `Check Command' to the Edit Host dialog.
* Plugins support started.
** Services-Tab plugin added.
** Bulk Tools Services plugin added.
** Bulk Tools Hosts plugin added.

03 Jul 2013 New version 1.157

* Fixes to get GUI working in Internet Explorer 8.

25 Jun 2013 New version 1.155

* Bug fixes
*   Fix for the 'Filter by hostgroup' box not updating the UI.

24 Jun 2013 New version 1.154

* Debian packaging fixes. Tested install procedure in debian 6.
* Jquery and theme update. Added tabs to edit dialogs to support extra options.

11 Jun 2013 New version 1.152

* Bug fixes
* New `Apply and Restart' window shows output from `csv2nag' and `nagios -v'.
* New `Service Sets' tab added.
* Can now change the service name when cloning a service.
* Service and serviceset commands can now contain any text.

06 Jun 2013 Show output from 'Apply Changes'

05 Jun 2013 Added ability to 'clone' to a new service name.
Cloning is back.

04 Jun 2013 The `servicedesc' and `command' fields are now urlencoded.
Cloning hosts and services is temporarily disabled!

27 May 2013 Added Service Sets page to GUI.

3 Apr 2013 Bug fixes. Moved code to github.

3 Feb 2013 New `testing' feature for distributed environments only.

14 Jan 2013 - New release with lots of enhancements and fixes. Packaging has changed: See `Install'.

7 Nov 2012 - All nagios object definitions are now supported in the REST api.

22 Oct 2012 - Fixes made for Centos 5/6 and Debian packages.

4 Sep 2012 - Added more Nagios directives to the REST api. See the `Upgrade' section below. 

21 Jul 2012 - http://blogger.smorg.co.uk/2012/07/nagrestconf-on-raspberry-pi.html[Nagrestconf on Raspberry PI]

20 Jul 2012 - https://sourceforge.net/projects/nagrestconf/files/Debian/[Debian package released to sourceforge]
